# Generated by Django 5.1.1 on 2025-09-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(blank=True, max_length=32, verbose_name='Ед. изм. (по умолч.)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=32, verbose_name='Ед. изм.'),
        ),
    ]
